### ISSUE TITLE
你这个很一般，也很复杂如果每个都需要去创建，有那功夫的时间早就创建好一个中间页了

### ISSUE THREAD

**Issue by a568640533** [likeyun/TbkTool#1]
你这个非常一般，只能说没什么用处，明明可以通过url获取口令显示的偏偏非得搞的需要后台创建口令，说白了这玩意也不能叫淘客中间页了。。只能说是一个带后台鸡肋残品，还不如你哪个活码系统！

**Comment by likeyun** [comment]
你不会做淘客就不要讨论这个东西。

--------------原始邮件--------------
发件人："a568640533 "<notifications@github.com&gt;;
发送时间：2020年10月19日(星期一) 上午8:14
收件人："likeyun/TbkTool" <TbkTool@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[likeyun/TbkTool] 你这个很一般，也很复杂如果每个都需要去创建，有那功夫的时间早就创建好一个中间页了 (#1)
-----------------------------------

 

 
你这个非常一般，只能说没什么用处，明明可以通过url获取口令显示的偏偏非得搞的需要后台创建口令，说白了这玩意也不能叫淘客中间页了。。只能说是一个带后台鸡肋残品，还不如你哪个活码系统！

**Comment by a568640533** [comment]
作者你已经飘了，而且思路都是已经歪了，中间页需要那么复杂吗？ 我不做会淘客？搞笑。自己做的东西都不咋滴还有B脸这样回复？给你评价，还这样回复？自己做的东西不行就是不行，别唧唧歪歪的，你见谁家的中间页是需要去后台一个一个创建的？ 就算是免单中间页没你怎么复杂的。

**Comment by likeyun** [comment]
呵呵。别人都是这么做的，就你不是这么做。你以为你很牛逼？你就是不懂，别听了不高兴。我的东西爱怎么做就怎么做你管得着？

--------------原始邮件--------------
发件人："a568640533 "<notifications@github.com&gt;;
发送时间：2020年10月25日(星期天) 上午6:00
收件人："likeyun/TbkTool" <TbkTool@noreply.github.com&gt;;
抄送："TANKING "<king@likeyunba.com&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [likeyun/TbkTool] 你这个很一般，也很复杂如果每个都需要去创建，有那功夫的时间早就创建好一个中间页了 (#1)
-----------------------------------

 

 
作者你已经飘了，而且思路都是已经歪了，中间页需要那么复杂吗？ 我不做会淘客？搞笑。自己做的东西都不咋滴还有B脸这样回复？给你评价，还这样回复？自己做的东西不行就是不行，别唧唧歪歪的，你见谁家的中间页是需要去后台一个一个创建的？ 就算是免单中间页没你怎么复杂的。

**Comment by likeyun** [comment]
自己不懂别人的想法还好意思去评论人家，你这脸皮也是够厚的。

--------------原始邮件--------------
发件人："a568640533 "<notifications@github.com&gt;;
发送时间：2020年10月25日(星期天) 上午6:00
收件人："likeyun/TbkTool" <TbkTool@noreply.github.com&gt;;
抄送："TANKING "<king@likeyunba.com&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [likeyun/TbkTool] 你这个很一般，也很复杂如果每个都需要去创建，有那功夫的时间早就创建好一个中间页了 (#1)
-----------------------------------

 

 
作者你已经飘了，而且思路都是已经歪了，中间页需要那么复杂吗？ 我不做会淘客？搞笑。自己做的东西都不咋滴还有B脸这样回复？给你评价，还这样回复？自己做的东西不行就是不行，别唧唧歪歪的，你见谁家的中间页是需要去后台一个一个创建的？ 就算是免单中间页没你怎么复杂的。
